version: 2

sources:
  - name: dwhvisualnext
    database: dwhvisualnext  # This points directly to your Databricks Foreign Catalog
    schema: analytics               # Your Azure SQL database schema name
    tables:
      - name: centric_product
        identifier: d_centricproduct

  - name: byod
    database: dwhvisualnext
    schema: d365_byod
    tables:
      - name: item_barcode
        identifier: Rev_InventItembarcodeStaging

      - name: inventory_combinations
        identifier: Rev_InventDimCombinationStaging

      - name: inventory_item
        identifier: Rev_InventTableStaging

      - name: inventory_module
        identifier: Rev_InventTableMODUleStaging

      - name: product_variant
        identifier: Rev_EcoResDistinctProductVariantStaging

      - name: hts_assignment
        identifier: REVCodesAssignmentStaging